$(document).ready(function(){
	/*自制的小屏下拉菜单*/
	$("#menu-click").click(function(){
		$("#menu-total").toggleClass("none");
	});
	$("#close").click(function(){
		$("#menu-total").toggleClass("none");
	});
});
